# This test is used to confirm that the pytest workflow fails on a failing test

def test_workflow():
    raise Exception()
